service: react-coffee-shop  # Your project name

provider:
  name: aws
  runtime: nodejs18.x
  region: ca-central-1  # Change to your region
  memorySize: 1024
  timeout: 30
  environment:
    NODE_ENV: production

functions:
  nextjsApp:
    handler: handler.handler  # This now points to handler.js
    events:
      - httpApi:
          path: /
          method: ANY
      - httpApi:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-nextjs

custom:
  serverless-nextjs:
    memory: 1024
    timeout: 30
    name: react-coffee-shop
    bucketName: react-coffee-shop-deployment
